language: php

php:
  - 5.5
  - 5.4
  - hhvm

install:
  - composer install

script: sh -c "if [ \"$TRAVIS_PHP_VERSION\" = '5.5' ]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi"

after_script:
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" = '5.5' ]; then wget https://scrutinizer-ci.com/ocular.phar; fi"
  - sh -c "if [ \"$TRAVIS_PHP_VERSION\" = '5.5' ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi"
